# -*- coding: utf-8 -*- 

"""
config.py
يحتوي هذا الملف على الثوابت والإعدادات العامة للتطبيق
"""

from pathlib import Path
from resource_helper import get_working_path

# ترجمات النصوص المستخدمة في التطبيق
TRANSLATIONS = {
    "ar": dict(sorted({
        "about": "حول",
        "adhan_sound_file": "ملف صوت الأذان",
        "all_files": "جميع الملفات",
        "app_error": "خطأ في التطبيق",
        "app_running_in_background": "التطبيق يعمل في الخلفية",
        "app_running_in_background_message": "لا يزال التطبيق يعمل. انقر على الأيقونة في شريط المهام لإظهاره.",
        "app_settings": "إعدادات التطبيق",
        "app_title": "🕌 مواقيت الصلاة",
        "arabic": "العربية",
        "asr": "العصر",
        "audio_files": "ملفات الصوت",
        "auto_update_interval": "فترة التحديث التلقائي (ثواني)",
        "browse": "تصفح",
        "cancel": "إلغاء",
        "city": "المدينة ",
        "city_en_name": "المدينة (اسم إنجليزي):",
        "connected": "متصل",
        "confirm": "تأكيد",
        "confirm_restore_defaults": "هل تريد استعادة جميع الإعدادات الافتراضية؟",
        "confirm_restore_and_restart": "سيتم استعادة الإعدادات الافتراضية وإعادة تشغيل التطبيق",
        "connection_error": "خطأ في الاتصال",
        "continue_later": "المتابعة لاحقاً",
        "country": "الدولة ",
        "country_en_name": "الدولة (اسم إنجليزي):",
        "current_time_label": "🕐 الوقت الحالي {time_str}",
        "custom_sound_file": "ملف الصوت المخصص",
        "dark": "داكن",
        "date_label": "📅 التاريخ {date_str}",
        "degrees": "درجة",
        "direction": "الاتجاه",
        "direction_is": "الاتجاه {direction_name}",
        "direction_label": "الاتجاه: --- درجة",
        "disconnected": "غير متصل",
        "dhuhr": "الظهر",
        "enable_adhan_sounds": "تفعيل أصوات الأذان",
        "enable_notifications": "تفعيل الإشعارات",
        "english": "English",
        "error": "خطأ",
        "error_opening_settings": "حدث خطأ في فتح نافذة الإعدادات",
        "failed_to_fetch_data": "فشل في جلب البيانات",
        "fajr": "الفجر",
        "fatal_app_error": "حدث خطأ فادح",
        "fatal_error": "خطأ فادح",
        "finished": "انتهت ✓",
        "free_for_the_sake_of_allah": "مجاناً لوجه الله تعالى",
        "general": "عام",
        "hour": "ساعة",
        "isha": "العشاء",
        "its_time_for_prayer": "حان الآن وقت أذان {prayer_name}",
        "language": "اللغة",
        "last_update": "آخر تحديث",
        "light": "فاتح",
        "loading_prayer_times": "...جاري تحميل مواقيت الصلاة ⏳",
        "location": "🌍 الموقع",
        "location_settings_title": "تحديد الموقع (سيتم تطبيقه عند إعادة التشغيل)",
        "logo_not_found": "لم يتم العثور على الشعار",
        "maghrib": "المغرب",
        "minute": "دقيقة",
        "minutes_remaining_for_prayer": "يتبقى {minutes} دقائق على أذان {prayer_name}",
        "no_cities": "لا توجد مدن",
        "no_server_response": "لا يوجد استجابة من الخادم",
        "no_sound_file_selected": "لم يتم تحديد ملف صوتي",
        "notifications": "الإشعارات",
        "notification_before_prayer": "الإشعار قبل الأذان (دقائق)",
        "notification_sound_file": "ملف صوت التنبيه",
        "now": "الآن ⏰",
        "play": "تشغيل",
        "please_select_city_country": "الرجاء تحديد المدينة والدولة أولاً في الإعدادات",
        "prayer_calculation_method": "طريقة حساب مواقيت الصلاة",
        "prayer_notification_alert": "تنبيه موقيت الصلاة",
        "prayer_status_finished": "انتهت ✓",
        "prayer_status_now": "الآن ⏰",
        "prayer_status_upcoming": "قادمة",
        "prayer_status_within_hour": "خلال {time_diff}د",
        "prayer_time": "وقت الصلاة",
        "prayer_times": "مواقيت الصلاة",
        "prayer_times_for_city": "مواقيت الصلاة لمدينة",
        "prayer_times_program": "برنامج مواقيت الصلاة",
        "prayer_times_table_title": "🕐 مواقيت الصلاة",
        "prayer_times_updated_successfully": "تم تحديث مواقيت الصلاة بنجاح",
        "programmed_by": "برمجة : محمود نصار",
        "qibla": "القبلة",
        "qibla_direction": "🧭 اتجاه القبلة",
        "qibla_direction_label": "الاتجاه {direction:.1f}°",
        "qibla_angle_from_north": "زاوية القبلة من الشمال",
        "set_arrow_towards_north": "اضبط اتجاه السهم الأحمر نحو الشمال الجغرافي",
        "qibla_info": "معلومات",
        "qibla_info_text": "        • يتم حساب اتجاه القبلة بناءً على موقع المدينة المختارة •\n        • الاتجاه محسوب بالنسبة للشمال الجغرافي•\n        • للحصول على دقة أكبر، تأكد من اتصالك بالإنترنت •\n        ",
        "remaining_time_on": "الوقت المتبقي على",
        "restart_now": "إعادة التشغيل الآن",
        "restart_required": "إعادة التشغيل مطلوبة",
        "restore_defaults": "استعادة الافتراضي",
        "save": "حفظ",
        "saved_successfully": "تم الحفظ",
        "searching": "جاري البحث...",
        "select_adhan_file": "اختر ملف الأذان",
        "settings": "⚙️ إعدادات",
        "settings_saved_successfully": "تم تغيير الإعدادات. إضغط لإعادة التشغيل أو الاستمرار حاليا وسيتم تطبيق الإعدادات عند إعادة التشغيل",
        "settings_saved_successfully_restart": "تم حفظ الإعدادات، بعض التغييرات تتطلب إعادة تشغيل التطبيق لتفعيلها.\nهل تريد إعادة التشغيل الآن؟",
        "show_qibla_direction": "إظهار اتجاه القبلة",
        "show_window": "إظهار",
        "sounds": "الأصوات",
        "stop": "إيقاف",
        "sunrise": "الشروق",
        "table_header_prayer": "الصلاة",
        "table_header_status": "الحالة",
        "table_header_time": "الوقت",
        "theme": "المظهر",
        "undefined": "غير محدد",
        "upcoming": "قادمة",
        "update": "تحديث",
        "updated_successfully": "تم التحديث",
        "version": "الإصدار",
        "version_label": "الإصدار : {version}",
        "volume": "مستوى الصوت",
        "quit": "خروج",
        "exit_confirmation": "تأكيد الخروج",
        "exit_confirmation_message": "هل أنت متأكد أنك تريد الخروج من التطبيق؟",
        "no": "لا",
        "yes": "نعم"
    }.items())),
    "en": dict(sorted({
        "about": "About",
        "adhan_sound_file": "Adhan Sound File",
        "all_files": "All Files",
        "app_error": "Application Error",
        "app_running_in_background": "Application is running in the background",
        "app_running_in_background_message": "The application is still running. Click the tray icon to show it.",
        "app_settings": "Application Settings",
        "app_title": "🕌 Prayer Times",
        "arabic": "العربية",
        "asr": "Asr",
        "audio_files": "Audio Files",
        "auto_update_interval": "Auto Update Interval (seconds)",
        "browse": "Browse",
        "cancel": "Cancel",
        "city": "City ",
        "city_en_name": "City (English name):",
        "connected": "Connected",
        "confirm": "Confirm",
        "confirm_restore_defaults": "Are you sure you want to restore all default settings?",
        "confirm_restore_and_restart": "Default settings will be restored and the application will be restarted",
        "connection_error": "Connection error",
        "continue_later": "Continue Later",
        "country": "Country ",
        "country_en_name": "Country (English name):",
        "current_time_label": "🕐 Current Time {time_str}",
        "custom_sound_file": "Custom Sound File",
        "dark": "Dark",
        "date_label": "📅 Date {date_str}",
        "degrees": "degrees",
        "direction": "Direction",
        "direction_is": "Direction {direction_name}",
        "direction_label": "Direction: --- degrees",
        "disconnected": "Disconnected",
        "dhuhr": "Dhuhr",
        "enable_adhan_sounds": "Enable Adhan Sounds",
        "enable_notifications": "Enable Notifications",
        "english": "English",
        "error": "Error",
        "error_opening_settings": "Error opening settings window",
        "failed_to_fetch_data": "Failed to fetch data",
        "fajr": "Fajr",
        "fatal_app_error": "A fatal error occurred",
        "fatal_error": "Fatal Error",
        "finished": "Finished ✓",
        "free_for_the_sake_of_allah": "Free for the sake of Allah",
        "general": "General",
        "hour": "hour",
        "isha": "Isha",
        "its_time_for_prayer": "It's time for {prayer_name} prayer",
        "language": "Language",
        "last_update": "Last update",
        "light": "Light",
        "loading_prayer_times": "⏳ Loading prayer times...",
        "location": "🌍 Location",
        "location_settings_title": "Set Location (applies on restart)",
        "logo_not_found": "Logo not found",
        "maghrib": "Maghrib",
        "minute": "minute",
        "minutes_remaining_for_prayer": "{minutes} minutes remaining for {prayer_name} prayer",
        "no_cities": "No cities found",
        "no_server_response": "No response from server",
        "no_sound_file_selected": "No sound file selected",
        "notifications": "Notifications",
        "notification_before_prayer": "Notify before prayer (minutes)",
        "notification_sound_file": "Notification Sound File",
        "now": "Now ⏰",
        "play": "Play",
        "please_select_city_country": "Please select the city and country first in the settings.",
        "prayer_calculation_method": "Prayer Times Calculation Method",
        "prayer_notification_alert": "Prayer Time Alert",
        "prayer_status_finished": "Finished ✓",
        "prayer_status_now": "Now ⏰",
        "prayer_status_upcoming": "Upcoming",
        "prayer_status_within_hour": "In {time_diff} min",
        "prayer_time": "Prayer Time",
        "prayer_times": "Prayer Times",
        "prayer_times_for_city": "Prayer times for",
        "prayer_times_program": "Prayer Times Program",
        "prayer_times_table_title": "🕐 Prayer Times",
        "prayer_times_updated_successfully": "Prayer times updated successfully",
        "programmed_by": "Programmed by: Mahmoud Nassar",
        "qibla": "Qibla",
        "qibla_direction": "🧭 Qibla Direction",
        "qibla_direction_label": "Direction {direction:.1f}°",
        "qibla_angle_from_north": "Qibla angle from North",
        "set_arrow_towards_north": "Set the red arrow towards the geographic North",
        "qibla_info": "Information",
        "qibla_info_text": "        • Qibla direction is calculated based on the selected city's location.\n        • The direction is calculated relative to True North.\n        • For better accuracy, ensure you are connected to the internet.\n        ",
        "remaining_time_on": "Time remaining for",
        "restart_now": "Restart Now",
        "restart_required": "Restart Required",
        "restore_defaults": "Restore Defaults",
        "save": "Save",
        "saved_successfully": "Saved",
        "searching": "Searching...",
        "select_adhan_file": "Select Adhan File",
        "settings": "⚙️ Settings",
        "settings_saved_successfully": "Settings have been changed. Click to restart or continue and settings will be applied on restart.",
        "settings_saved_successfully_restart": "Settings saved. Some changes require a restart to take effect.\nDo you want to restart now?",
        "show_qibla_direction": "Show Qibla Direction",
        "show_window": "Show",
        "sounds": "Sounds",
        "stop": "Stop",
        "sunrise": "Sunrise",
        "table_header_prayer": "Prayer",
        "table_header_status": "Status",
        "table_header_time": "Time",
        "theme": "Theme",
        "undefined": "Undefined",
        "upcoming": "Upcoming",
        "update": "Update",
        "updated_successfully": "Updated",
        "version": "Version",
        "version_label": "Version: {version}",
        "volume": "Volume",
        "quit": "Quit",
        "exit_confirmation": "Exit Confirmation",
        "exit_confirmation_message": "Are you sure you want to exit the application?",
        "no": "No",
        "yes": "Yes"
    }.items()))
}


# طرق حساب مواقيت الصلاة
CALCULATION_METHODS = {
    "جامعة العلوم الإسلامية - كراتشي": 1,
    "الجمعية الإسلامية لأمريكا الشمالية": 2,
    "رابطة العالم الإسلامي": 3,
    "أم القرى - مكة المكرمة": 4,
    "الهيئة المصرية العامة للمساحة": 5,
    "جامعة طهران للعلوم": 7,
    "معهد الجيوفيزياء - جامعة طهران": 8,
    "الخليج - دولة الإمارات": 9,
    "الكويت": 10,
    "قطر": 11,
    "مجلس الشورى الإسلامي الأعلى - الجزائر": 12,
    "فرنسا - اتحاد المنظمات الإسلامية": 13,
    "تركيا - رئاسة الشؤون الدينية": 14,
    "روسيا - المجلس الديني": 15
}
CALCULATION_METHODS_REV = {v: k for k, v in CALCULATION_METHODS.items()}

CALCULATION_METHODS_EN = {
    "University of Islamic Sciences, Karachi": 1,
    "Islamic Society of North America": 2,
    "Muslim World League": 3,
    "Umm Al-Qura University, Makkah": 4,
    "Egyptian General Authority of Survey": 5,
    "University of Tehran": 7,
    "Institute of Geophysics, University of Tehran": 8,
    "Gulf Region": 9,
    "Kuwait": 10,
    "Qatar": 11,
    "Algerian Ministry of Religious Affairs and Wakfs": 12,
    "Union of Islamic Organisations of France": 13,
    "Presidency of Religious Affairs, Turkey": 14,
    "Spiritual Administration of Muslims of Russia": 15
}
CALCULATION_METHODS_EN_REV = {v: k for k, v in CALCULATION_METHODS_EN.items()}

# تحديد المسار الجذري للمشروع لضمان استقلالية المسارات
APP_DATA_DIR = Path(get_working_path('.'))

# المسارات للملفات والمجلدات الرئيسية
SETTINGS_FILE = APP_DATA_DIR / 'settings.json'
CACHE_DIR = APP_DATA_DIR / 'cache'
LOG_DIR = APP_DATA_DIR / 'logs'
LOG_FILE = LOG_DIR / 'prayer_app.log'
COUNTRIES_FILE = APP_DATA_DIR / 'countries.json'
COUNTRIES_CACHE_FILE = CACHE_DIR / 'countries.json'
CITIES_CACHE_DIR = CACHE_DIR / 'cities_cache'
WORLD_CITIES_DIR = APP_DATA_DIR / 'world_cities'
SOUNDS_DIR = APP_DATA_DIR / 'sounds'

# تأكد من وجود مجلدات التخزين المؤقت والسجلات
CACHE_DIR.mkdir(exist_ok=True)
CITIES_CACHE_DIR.mkdir(exist_ok=True)
LOG_DIR.mkdir(exist_ok=True)

class Translator:
    def __init__(self, language="ar"):
        self.language = language
        if language not in TRANSLATIONS:
            self.language = "en"

    def set_language(self, language):
        if language in TRANSLATIONS:
            self.language = language

    def get(self, key, **kwargs):
        translation = TRANSLATIONS.get(self.language, {}).get(key, key)
        if kwargs:
            return translation.format(**kwargs)
        return translation
